name: CI - On Release
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  Artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: artifactory
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Add environment variables
        run: |
          echo "username=${{secrets.ARTIFACTORY_USERNAME}}" >> gradle.properties
          echo "password=${{secrets.ARTIFACTORY_PASSWORD}}" >> gradle.properties 
          echo "zds-android-maven=${{secrets.ZDS_ANDROID_MAVEN}}" >> gradle.properties
      - name: Publish
        run: gradle publish -P publish=dev
